# Generated by Django 4.2.7 on 2025-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence')], default='absent', help_text='Attendance status', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, help_text='Time student checked in', null=True)),
                ('check_in_method', models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual', 'Manual Entry'), ('api', 'API')], default='face_recognition', help_text='Method of attendance recording', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('confidence_score', models.FloatField(blank=True, help_text='Face recognition confidence score (0-1)', null=True)),
                ('liveness_verified', models.BooleanField(default=False, help_text='Whether liveness check passed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-created_at', 'student__roll_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('excused_count', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance session')),
                ('start_time', models.TimeField(help_text='Session start time')),
                ('end_time', models.TimeField(blank=True, help_text='Session end time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
