# Generated by Django 4.2.7 on 2025-11-15 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('max_students', models.PositiveIntegerField(default=50, help_text='Maximum number of students')),
                ('is_active', models.BooleanField(default=True, help_text='Course active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, help_text='Course instructor', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_number', models.CharField(help_text='Student roll number', max_length=50, unique=True)),
                ('face_embedding', models.BinaryField(blank=True, help_text='Stored face embedding (numpy array as binary)', null=True)),
                ('face_encoding_updated_at', models.DateTimeField(blank=True, help_text='Last time face encoding was updated', null=True)),
                ('is_face_registered', models.BooleanField(default=False, help_text='Whether student has registered face')),
                ('department', models.CharField(blank=True, help_text='Student department', max_length=100)),
                ('semester', models.PositiveIntegerField(default=1, help_text='Current semester')),
                ('registration_date', models.DateField(auto_now_add=True, help_text='Date of registration')),
                ('is_active', models.BooleanField(default=True, help_text='Student active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['roll_number'],
                'indexes': [models.Index(fields=['roll_number'], name='student_stu_roll_nu_3ac433_idx'), models.Index(fields=['is_face_registered'], name='student_stu_is_face_f89479_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_faces/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('is_verified', models.BooleanField(default=False, help_text='Whether image was verified as correct face')),
                ('is_training_data', models.BooleanField(default=True, help_text='Whether image is used in training dataset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Face Image',
                'verbose_name_plural': 'Student Face Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_training_data'], name='student_stu_student_a4ca03_idx'), models.Index(fields=['-created_at'], name='student_stu_created_6f2dc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enrollment active status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.studentprofile')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'indexes': [models.Index(fields=['student', 'course'], name='student_enr_student_6531e6_idx'), models.Index(fields=['is_active'], name='student_enr_is_acti_15b2cb_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='student_cou_code_ceb3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='student_cou_is_acti_57ad6d_idx'),
        ),
    ]
